I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/credits.rpy", line 22, in <module>
NameError: name 'credits_speed' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/credits.rpyc", line 22, in script
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\ast.py", line 1011, in execute
    img = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\python.py", line 1983, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/credits.rpy", line 22, in <module>
NameError: name 'credits_speed' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.0.271
 
Fri Jun 28 22:23:43 2019
