I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Credits.rpy", line 26, in script
    init python:
  File "game/Credits.rpy", line 30, in <module>
    for c in credits:
NameError: name 'credits' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Credits.rpy", line 26, in script
    init python:
  File "E:\2D game\RenPy\renpy-7.1.1-sdk\renpy\ast.py", line 912, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\2D game\RenPy\renpy-7.1.1-sdk\renpy\python.py", line 1959, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/Credits.rpy", line 30, in <module>
    for c in credits:
NameError: name 'credits' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.0.271
 
Sat Jun 29 00:07:02 2019
